language: go
sudo: required
go:
  - 1.7.3
install:
  - go get github.com/Masterminds/glide
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/glide install
  - $HOME/gopath/bin/overalls -project=github.com/mikoim/steam-jp-finder -covermode=count -ignore=.git,vendor -debug -- -race -v
  - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
